name: Add Products
description: Submit a request to add products
title: "[Global-Catalog: Add Products]: "
labels: ["add-products"]
body:
  - type: dropdown
    id: reason
    attributes:
      label: Reason
      description: Select the reason for this request
      options:
        - "-- select one --"
        - New SKUs Received
        - New Pack Sizes Received
    validations:
      required: true
  
  - type: dropdown
    id: base
    attributes:
      label: Base
      description: Select the base
      options:
        - "-- select one --"
        - bayer
        - corteva
        - syngenta
        - winfield
        - rosens
        - chs
        - amvac
        - basf
        - fmc
        - upl
        - valent
        - helena
        - gowan
        - albaugh
        - atticus
        - van_diest
        - cni
        - nutrien
        - simplot
        - iap
    validations:
      required: true

  - type: textarea
    id: sku-information
    attributes:
      label: SKU Information
      placeholder: Enter SKU information...
    validations:
      required: true


  - type: textarea
    id: other-details
    attributes:
      label: Other Details
      placeholder: Enter any additional details...
    validations:
      required: false
