name: New Program Configuration
description: Submit a request to configure a new program
title: "[New Program Configuration]: "
labels: ["new-program-configuration"]
body:
  - type: input
    id: participant-key
    attributes:
      label: Participant Key
      placeholder: Enter the participant key...
    validations:
      required: true

  - type: dropdown
    id: reason
    attributes:
      label: Reason
      description: Select the reason for this request
      options:
        - New Customer Request
    validations:
      required: true

  - type: input
    id: time-frame
    attributes:
      label: Time Frame
      placeholder: Enter the time frame...
    validations:
      required: false

  - type: input
    id: program-name
    attributes:
      label: Program Name
      placeholder: Enter the program name...
    validations:
      required: true

  - type: dropdown
    id: program-supplier
    attributes:
      label: Program Supplier
      description: Select the program supplier
      options:
        - "-- select one --"
        - bayer
        - corteva
        - syngenta
        - winfield
        - rosens
        - chs
        - amvac
        - basf
        - fmc
        - upl
        - valent
        - helena
        - gowan
        - albaugh
        - atticus
        - van_diest
        - cni
        - nutrien
        - simplot
        - iap
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other Details
      placeholder: Enter any additional details...
    validations:
      required: false
