name: Assign Task Workflow

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  assign-task:
    runs-on: ubuntu-latest

    steps:
      - name: Assign a task to someone
        uses: actions/github-script@v6
        with:
          script: |
            const issueTitle = "Assigned Task";
            const issueBody = "This is a task assigned to a specific user.";
            const assignee = "llmartella"; // Replace with the GitHub username of the assignee

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              assignees: [llmartella],
            });

permissions:
  issues: write
