name: Create Issue and Add to Classic Project

on:
  workflow_dispatch:

jobs:
  create_issue_and_add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: cli/cli-action@v2

      - name: Create issue
        id: create_issue
        run: |
          TITLE="Monthly Report - $(date +'%B')"
          BODY=$'- [ ] Task 1\n- [ ] Task 2\n- [ ] Task 3'
          ISSUE_JSON=$(gh issue create \
            --title "$TITLE" \
            --body "$BODY" \
            --label "automation" \
            --assignee "llmartella" \
            --repo llmartella/alletram \
            --json number,id)
          echo "$ISSUE_JSON"
          echo "issue_number=$(echo $ISSUE_JSON | jq .number)" >> $GITHUB_OUTPUT
          echo "issue_id=$(echo $ISSUE_JSON | jq -r .id)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get project and column IDs
        id: get_project_info
        run: |
          PROJECT_ID=$(gh api repos/amfaro/REPO_NAME/projects --jq '.[] | select(.name=="kanban") | .id')
          COLUMN_ID=$(gh api repos/amfaro/REPO_NAME/projects/$PROJECT_ID/columns --jq '.[] | select(.name=="Ready") | .id')
          echo "project_id=$PROJECT_ID" >> $GITHUB_OUTPUT
          echo "column_id=$COLUMN_ID" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add issue to project column
        run: |
          gh api repos/amfaro/REPO_NAME/projects/${{ steps.get_project_info.outputs.project_id }}/columns/${{ steps.get_project_info.outputs.column_id }}/cards \
            -f content_id=${{ steps.create_issue.outputs.issue_id }} \
            -f content_type=Issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
