name: Create Issue and Assign to Project

on:
  # You can trigger this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      issue_title:
        description: 'Issue title'
        required: true
      issue_body:
        description: 'Issue body'
        required: true
      issue_labels:
        description: 'Issue labels (comma-separated)'
        required: false
  # Or you can set up other triggers
  # For example, to run on push to main branch:
  # push:
  #   branches: [ main ]

jobs:
  create-issue-and-assign-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        id: create-issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Using context.repo to get the current repository information
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            console.log(`Creating issue in $llmartella/$alletram`);
            
            try {
              const { data: issue } = await github.rest.issues.create({
                owner: owner,
                repo: repo,
                title: '${{ github.event.inputs.issue_title || 'Automated Issue' }}',
                body: '${{ github.event.inputs.issue_body || 'This issue was automatically created by the GitHub Action workflow.' }}',
                labels: '${{ github.event.inputs.issue_labels }}'.split(',').filter(Boolean).map(label => label.trim())
              });
              console.log(`Created issue #${issue.number}: ${issue.title}`);
              return { issue_number: issue.number, issue_id: issue.node_id };
            } catch (error) {
              console.log('Error creating issue:');
              console.log(error);
              core.setFailed(error.message);
              return {};
            }

      - name: Add Issue to Project
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PROJECTS_TOKEN_1 }} # Personal access token with project permissions
          script: |
            // Get the issue ID from the previous step
            const issueId = JSON.parse(process.env.ISSUE_ID || '{}').issue_id;
            const projectId = 'PVT_kwHODDdG4s4A194P'; // Replace with your project ID
            
            if (!issueId) {
              core.setFailed('Issue ID not found');
              return;
            }
            
            // GraphQL mutation to add the issue to the project
            const addToProjectMutation = `
              mutation {
                addProjectV2ItemById(input: {
                  projectId: "${projectId}"
                  contentId: "${issueId}"
                }) {
                  item {
                    id
                  }
                }
              }
            `;
            
            try {
              const result = await github.graphql(addToProjectMutation);
              console.log('Issue added to project successfully');
              console.log(result);
            } catch (error) {
              console.log('Error adding issue to project:');
              console.log(error);
              core.setFailed(error.message);
            }
        env:
          ISSUE_ID: ${{ steps.create-issue.outputs.result }}
