name: Create Issue and Assign to Project

on:
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  issues: write
  contents: read

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create an issue and assign it to a project
        uses: actions/github-script@v6
        with:
          script: |
            // Step 1: Create the issue
            const { data: issue } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "LM test 1", // Replace with your issue title
              body: `
              ### Task Details
              - [ ] Task 1
              - [ ] Task 2
              - [ ] Task 3
              `, // Replace with your issue body
              assignees: ["llmartella"], // Replace with the GitHub username
              labels: ["agvend"], // Replace with your desired label
            });

            console.log("Created issue:", issue);

            // Step 2: Add the issue to a GitHub Project (v2) using GraphQL
            const projectId = "PVT_kwHODDdG4s4A194P"; // Replace with your project ID
            const mutation = `
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `;

            const variables = {
              projectId: projectId,
              contentId: issue.node_id, // Use the issue's node_id for GraphQL
            };

            const result = await github.graphql(mutation, variables);
            console.log("Issue added to project:", result);
